// Code generated by go-swagger; DO NOT EDIT.

package registers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/ConsenSys/fc-retrieval-register/models"
)

// NewAddRegisterParams creates a new AddRegisterParams object
// no default values defined in spec.
func NewAddRegisterParams() AddRegisterParams {

	return AddRegisterParams{}
}

// AddRegisterParams contains all the bound params for the add register operation
// typically these are obtained from a http.Request
//
// swagger:parameters addRegister
type AddRegisterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Add a register
	  Required: true
	  In: body
	*/
	Register *models.Register
	/*Register type
	  Required: true
	  In: path
	*/
	Type string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddRegisterParams() beforehand.
func (o *AddRegisterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Register
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("register", "body", ""))
			} else {
				res = append(res, errors.NewParseError("register", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Register = &body
			}
		}
	} else {
		res = append(res, errors.Required("register", "body", ""))
	}
	rType, rhkType, _ := route.Params.GetOK("type")
	if err := o.bindType(rType, rhkType, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindType binds and validates parameter Type from path.
func (o *AddRegisterParams) bindType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Type = raw

	if err := o.validateType(formats); err != nil {
		return err
	}

	return nil
}

// validateType carries on validations for parameter Type
func (o *AddRegisterParams) validateType(formats strfmt.Registry) error {

	if err := validate.EnumCase("type", "path", o.Type, []interface{}{"gateway", "provider"}, true); err != nil {
		return err
	}

	return nil
}
