version: 2.1

jobs:
  utest:
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/ConsenSys/fc-retrieval-register/
    steps:
      - checkout
      - run: make utest
  
  coverage:
    environment:
      CODE_COVERAGE: 0
    docker:
      - image: circleci/golang:1.16
    working_directory: /go/src/github.com/ConsenSys/fc-retrieval-register/
    steps:
      - checkout
      - run:
          name: Check code coverage
          command: |
            make coverage COV=$CODE_COVERAGE

  publishDocker:
    environment:
      IMAGE_NAME: consensys/fc-retrieval-register
      IMAGE_VERSION: dev
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$IMAGE_VERSION .
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKER_PASSWORD_RW" | docker login -u "$DOCKER_USER_RW" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_VERSION

workflows:
  version: 2
  release:
    jobs:
      - utest
      - coverage:
          requires:
            - utest
      - publishDocker:
          filters:
            branches:
              only: main
          context:
            - dockerhub-quorumengineering-rw
          requires:
            - coverage
