version: 2.1

jobs:
  publishDocker:
    environment:
      REGISTRY: consensys/
      IMAGE_NAME: consensys/fc-retrieval-register
      IMAGE_VERSION: dev
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            make build REGISTRY=$REGISTRY VERSION=$IMAGE_VERSION
      - run:
          name: Publish Docker image
          command: |
            echo "$DOCKER_PASSWORD_RW" | docker login -u "$DOCKER_USER_RW" --password-stdin
            docker push $IMAGE_NAME:$IMAGE_VERSION

workflows:
  version: 2
  release:
    jobs:
      - publishDocker:
          filters:
            branches:
              only: main
          context:
            - dockerhub-quorumengineering-rw
