// Code generated by go-swagger; DO NOT EDIT.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/ConsenSys/fc-retrieval-register/models"
)

// NewAddProviderRegisterParams creates a new AddProviderRegisterParams object
//
// There are no default values defined in the spec.
func NewAddProviderRegisterParams() AddProviderRegisterParams {

	return AddProviderRegisterParams{}
}

// AddProviderRegisterParams contains all the bound params for the add provider register operation
// typically these are obtained from a http.Request
//
// swagger:parameters addProviderRegister
type AddProviderRegisterParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Add a Provider register
	  Required: true
	  In: body
	*/
	Register *models.ProviderRegister
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddProviderRegisterParams() beforehand.
func (o *AddProviderRegisterParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ProviderRegister
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("register", "body", ""))
			} else {
				res = append(res, errors.NewParseError("register", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(context.Background())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Register = &body
			}
		}
	} else {
		res = append(res, errors.Required("register", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
