// Code generated by go-swagger; DO NOT EDIT.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ConsenSys/fc-retrieval-register/models"
)

// DeleteProviderRegisterOKCode is the HTTP code returned for type DeleteProviderRegisterOK
const DeleteProviderRegisterOKCode int = 200

/*DeleteProviderRegisterOK Provider registers deleted

swagger:response deleteProviderRegisterOK
*/
type DeleteProviderRegisterOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ack `json:"body,omitempty"`
}

// NewDeleteProviderRegisterOK creates DeleteProviderRegisterOK with default headers values
func NewDeleteProviderRegisterOK() *DeleteProviderRegisterOK {

	return &DeleteProviderRegisterOK{}
}

// WithPayload adds the payload to the delete provider register o k response
func (o *DeleteProviderRegisterOK) WithPayload(payload *models.Ack) *DeleteProviderRegisterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete provider register o k response
func (o *DeleteProviderRegisterOK) SetPayload(payload *models.Ack) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProviderRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteProviderRegisterDefault Internal error

swagger:response deleteProviderRegisterDefault
*/
type DeleteProviderRegisterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteProviderRegisterDefault creates DeleteProviderRegisterDefault with default headers values
func NewDeleteProviderRegisterDefault(code int) *DeleteProviderRegisterDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteProviderRegisterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete provider register default response
func (o *DeleteProviderRegisterDefault) WithStatusCode(code int) *DeleteProviderRegisterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete provider register default response
func (o *DeleteProviderRegisterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete provider register default response
func (o *DeleteProviderRegisterDefault) WithPayload(payload *models.Error) *DeleteProviderRegisterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete provider register default response
func (o *DeleteProviderRegisterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteProviderRegisterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
