version: "3.8"

services:
  fc-retrieval-register:
    container_name: fc-retrieval-register
    build:
      dockerfile: Dockerfile.dev
      context: .
    networks:
      - shared
    ports:
      - "8090:8090"
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped

  fc-retrieval-redis:
    image: "redis:alpine"
    container_name: fc-retrieval-redis
    networks:
      - shared
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

networks:
  shared:
    name: shared
    external: true
