version: "3"
services:
  fc-retrieval-register:
    image: fc-retrieval-register:v1
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    networks:
      - retrievalnetwork
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - retrievalnetwork
    restart: always

networks:
  retrievalnetwork:
