version: '3.7'

services:
  fc-retrieval-register:
    image: consensys/fc-retrieval-register:dev
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    networks:
      - shared
    restart: unless-stopped

  redis:
    container_name: fc-retrieval-redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shared
    restart: always

networks:
  shared:
    name: shared
    external: true