version: "3.8"

services:
  register:
    container_name: fc-retrieval-register
    build:
      dockerfile: ./fc-retrieval-register/Dockerfile.dev
      context: ../
    networks:
      - shared
    ports:
      - "9020:9020"
    volumes:
      - ../fc-retrieval-register:/go/src/fc-retrieval-register
      - ../fc-retrieval-register/${GO_MOD}:/go/src/fc-retrieval-register/go.mod
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: fc-retrieval-redis
    networks:
      - shared
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always

networks:
  shared:
    name: shared
    external: true
