FROM golang:latest

RUN apt-get update && apt-get install make bash

WORKDIR /go/src/

COPY . .

WORKDIR /go/src/fc-retrieval-register/

RUN go mod download -x

COPY --from=itinance/swag /root/swag /usr/local/bin

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -exclude-dir=.git -exclude-dir=docs --build="make build-dev" --command="./main --host=0.0.0.0 --port=9020"