# Copyright (C) 2020 ConsenSys Software Inc
FROM golang:1.15-alpine
RUN apk add --no-cache make gcc musl-dev linux-headers git
WORKDIR /go/src/app
COPY . .
# Remove any cached dependancies. TODO is this really needed?
# RUN go clean -modcache
# RUN go mod download -x
CMD go test -v  internal/integration/poc1usage_test.go