// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Retrieval Providers and Retrieval Gateways register.\n",
    "title": "Filecoin Retrieval Register",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Homepage"
        ],
        "summary": "Homepage",
        "operationId": "homepage",
        "responses": {
          "200": {
            "description": "homepage response",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "user validation error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers": {
      "get": {
        "description": "\u003cb\u003eGet register list\u003c/b\u003e",
        "tags": [
          "Registers"
        ],
        "summary": "Get register list",
        "operationId": "getRegisters",
        "responses": {
          "200": {
            "description": "Register list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Register"
              }
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "\u003cb\u003eAdd a register\u003c/b\u003e",
        "tags": [
          "Registers"
        ],
        "summary": "Add a register",
        "operationId": "addRegister",
        "parameters": [
          {
            "description": "Add a register",
            "name": "register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Register"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Register added",
            "schema": {
              "$ref": "#/definitions/Register"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Ack": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "Register": {
      "description": "Register entry",
      "type": "object",
      "properties": {
        "address": {
          "description": "Filecoin Account to be used with payment channels.",
          "type": "string"
        },
        "networkInfo": {
          "description": "Network addressing information.",
          "type": "string"
        },
        "regionCode": {
          "description": "Region Code.",
          "type": "string"
        },
        "rootSigningKey": {
          "description": "Retrieval provider Root Signing Public Key.",
          "type": "string"
        },
        "sigingKey": {
          "description": "Used for signing CID Group Offers and Single CID Offers.",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Retrieval Providers and Retrieval Gateways register.\n",
    "title": "Filecoin Retrieval Register",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Homepage"
        ],
        "summary": "Homepage",
        "operationId": "homepage",
        "responses": {
          "200": {
            "description": "homepage response",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "user validation error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers": {
      "get": {
        "description": "\u003cb\u003eGet register list\u003c/b\u003e",
        "tags": [
          "Registers"
        ],
        "summary": "Get register list",
        "operationId": "getRegisters",
        "responses": {
          "200": {
            "description": "Register list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Register"
              }
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "\u003cb\u003eAdd a register\u003c/b\u003e",
        "tags": [
          "Registers"
        ],
        "summary": "Add a register",
        "operationId": "addRegister",
        "parameters": [
          {
            "description": "Add a register",
            "name": "register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Register"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Register added",
            "schema": {
              "$ref": "#/definitions/Register"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Ack": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "Register": {
      "description": "Register entry",
      "type": "object",
      "properties": {
        "address": {
          "description": "Filecoin Account to be used with payment channels.",
          "type": "string"
        },
        "networkInfo": {
          "description": "Network addressing information.",
          "type": "string"
        },
        "regionCode": {
          "description": "Region Code.",
          "type": "string"
        },
        "rootSigningKey": {
          "description": "Retrieval provider Root Signing Public Key.",
          "type": "string"
        },
        "sigingKey": {
          "description": "Used for signing CID Group Offers and Single CID Offers.",
          "type": "string"
        }
      }
    }
  }
}`))
}
