// Code generated by go-swagger; DO NOT EDIT.

package provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetProviderRegistersParams creates a new GetProviderRegistersParams object
//
// There are no default values defined in the spec.
func NewGetProviderRegistersParams() GetProviderRegistersParams {

	return GetProviderRegistersParams{}
}

// GetProviderRegistersParams contains all the bound params for the get provider registers operation
// typically these are obtained from a http.Request
//
// swagger:parameters getProviderRegisters
type GetProviderRegistersParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetProviderRegistersParams() beforehand.
func (o *GetProviderRegistersParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
