swagger: "2.0"
info:
  title: Filecoin Retrieval Register
  version: "0.0.1"
  description: |
    Retrieval Providers and Retrieval Gateways register.
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http

basePath: /

paths:
  # Homepage
  /:
    get:
      tags:
        - Homepage
      summary: Homepage
      operationId: homepage
      responses:
        200:
          description: homepage response
          schema:
            $ref: "#/definitions/Ack"
        default:
          description: user validation error
          schema:
            $ref: "#/definitions/Error"
  # Registers
  /registers/gateway:
    post:
      tags:
        - Gateway
      summary: Add a Gateway register
      operationId: addGatewayRegister
      description: <b>Add a Gateway register</b>
      parameters:
        - in: "body"
          name: "register"
          description: "Add a Gateway register"
          required: true
          schema:
            $ref: "#/definitions/GatewayRegister"
      responses:
        200:
          description: Gateway register added
          schema:
            $ref: "#/definitions/GatewayRegister"
        default:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"
    get:
      tags:
        - Gateway
      summary: Get register list
      operationId: getGatewayRegisters
      description: <b>Get Gateway register list</b>
      responses:
        200:
          description: Gateway register list
          schema:
            type: "array"
            items:
              $ref: "#/definitions/GatewayRegister"
        default:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

  /registers/provider:
    post:
      tags:
        - Provider
      summary: Add a Provider register
      operationId: addProviderRegister
      description: <b>Add a Provider register</b>
      parameters:
        - in: "body"
          name: "register"
          description: "Add a Provider register"
          required: true
          schema:
            $ref: "#/definitions/ProviderRegister"
      responses:
        200:
          description: Provider register added
          schema:
            $ref: "#/definitions/ProviderRegister"
        default:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"
    get:
      tags:
        - Provider
      summary: Get Provider register list
      operationId: getProviderRegisters
      description: <b>Get Provider register list</b>
      responses:
        200:
          description: Provider register list
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ProviderRegister"
        default:
          description: Internal error
          schema:
            $ref: "#/definitions/Error"

definitions:
  # Registers
  GatewayRegister:
    type: object
    description: Register entry
    properties:
      nodeId:
        type: string
        description: Node ID.
      address:
        type: string
        description: Filecoin Account to be used with payment channels.
      rootSigningKey:
        type: string
        description: Retrieval provider Root Signing Public Key.
      sigingKey:
        type: string
        description: Used for signing CID Group Offers and Single CID Offers.
      networkInfoGateway:
        type: string
        description: Gateway network addressing information.
      networkInfoProvider:
        type: string
        description: Provider network addressing information.
      networkInfoClient:
        type: string
        description: Client network addressing information.
      networkInfoAdmin:
        type: string
        description: Admin network addressing information.
      regionCode:
        type: string
        description: Region Code.

  ProviderRegister:
    type: object
    description: Register entry
    properties:
      nodeId:
        type: string
        description: Node ID.
      address:
        type: string
        description: Filecoin Account to be used with payment channels.
      rootSigningKey:
        type: string
        description: Retrieval provider Root Signing Public Key.
      sigingKey:
        type: string
        description: Used for signing CID Group Offers and Single CID Offers.
      networkInfo:
        type: string
        description: Network addressing information.
      regionCode:
        type: string
        description: Region Code.

  # Responses
  Ack:
    type: object
    properties:
      status:
        type: string
      message:
        type: string

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
    required:
      - code
      - message
  Principal:
    type: string
