// Code generated by go-swagger; DO NOT EDIT.

package homepage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// HomepageHandlerFunc turns a function with the right signature into a homepage handler
type HomepageHandlerFunc func(HomepageParams) middleware.Responder

// Handle executing the request and returning a response
func (fn HomepageHandlerFunc) Handle(params HomepageParams) middleware.Responder {
	return fn(params)
}

// HomepageHandler interface for that can handle valid homepage params
type HomepageHandler interface {
	Handle(HomepageParams) middleware.Responder
}

// NewHomepage creates a new http.Handler for the homepage operation
func NewHomepage(ctx *middleware.Context, handler HomepageHandler) *Homepage {
	return &Homepage{Context: ctx, Handler: handler}
}

/*Homepage swagger:route GET / Homepage homepage

Homepage

*/
type Homepage struct {
	Context *middleware.Context
	Handler HomepageHandler
}

func (o *Homepage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewHomepageParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
