name: Publish Docker image
on:
  pull_request:
    branches: [main]
env:
  docker_registry: docker.pkg.github.com
  docker_image_name: fc-retrieval-register
  docker_image_version: pr-${{ github.event.number }}
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment variables
        run: |
          echo "Using docker_registry: $docker_registry"
          echo "Using docker_image_name: $docker_image_name"
          echo "Using docker_image_version: $docker_image_version"
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Echo Docker image
        run: echo "Building image $docker_image_name:$docker_image_version"
      - name: Build Docker image
        run: make build REGISTRY=$docker_registry/${{ github.repository }}/ VERSION=$docker_image_version
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push $docker_registry/${{ github.repository }}/$docker_image_name:$docker_image_version