// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Retrieval Providers and Retrieval Gateways register.\n",
    "title": "Filecoin Retrieval Register",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Homepage"
        ],
        "summary": "Homepage",
        "operationId": "homepage",
        "responses": {
          "200": {
            "description": "homepage response",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "user validation error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers/gateway": {
      "get": {
        "description": "\u003cb\u003eGet Gateway register list\u003c/b\u003e",
        "tags": [
          "Gateway"
        ],
        "summary": "Get register list",
        "operationId": "getGatewayRegisters",
        "responses": {
          "200": {
            "description": "Gateway register list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GatewayRegister"
              }
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "\u003cb\u003eAdd a Gateway register\u003c/b\u003e",
        "tags": [
          "Gateway"
        ],
        "summary": "Add a Gateway register",
        "operationId": "addGatewayRegister",
        "parameters": [
          {
            "description": "Add a Gateway register",
            "name": "register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GatewayRegister"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Gateway register added",
            "schema": {
              "$ref": "#/definitions/GatewayRegister"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "\u003cb\u003eDelete Gateway registers\u003c/b\u003e",
        "tags": [
          "Gateway"
        ],
        "summary": "Delete Gateway registers",
        "operationId": "deleteGatewayRegister",
        "responses": {
          "200": {
            "description": "Gateway registers deleted",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers/gateway/{id}": {
      "get": {
        "description": "\u003cb\u003eGet a provider gateway by Id\u003c/b\u003e",
        "tags": [
          "Gateway"
        ],
        "summary": "Get registered Gateway by Id",
        "operationId": "getGatewayRegistersById",
        "parameters": [
          {
            "type": "string",
            "description": "Gateway ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get a registered gateway by Id",
            "schema": {
              "$ref": "#/definitions/GatewayRegister"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers/provider": {
      "get": {
        "description": "\u003cb\u003eGet Provider register list\u003c/b\u003e",
        "tags": [
          "Provider"
        ],
        "summary": "Get Provider register list",
        "operationId": "getProviderRegisters",
        "responses": {
          "200": {
            "description": "Provider register list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ProviderRegister"
              }
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "\u003cb\u003eAdd a Provider register\u003c/b\u003e",
        "tags": [
          "Provider"
        ],
        "summary": "Add a Provider register",
        "operationId": "addProviderRegister",
        "parameters": [
          {
            "description": "Add a Provider register",
            "name": "register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProviderRegister"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Provider register added",
            "schema": {
              "$ref": "#/definitions/ProviderRegister"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "\u003cb\u003eDelete Provider registers\u003c/b\u003e",
        "tags": [
          "Provider"
        ],
        "summary": "Delete Provider registers",
        "operationId": "deleteProviderRegister",
        "responses": {
          "200": {
            "description": "Provider registers deleted",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers/provider/{id}": {
      "get": {
        "description": "\u003cb\u003eGet a provider register by Id\u003c/b\u003e",
        "tags": [
          "Provider"
        ],
        "summary": "Get registered Provider by Id",
        "operationId": "getProviderRegistersById",
        "parameters": [
          {
            "type": "string",
            "description": "Register ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get a registered provider by Id",
            "schema": {
              "$ref": "#/definitions/ProviderRegister"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Ack": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "GatewayRegister": {
      "description": "Register entry",
      "type": "object",
      "properties": {
        "address": {
          "description": "Filecoin Account to be used with payment channels.",
          "type": "string"
        },
        "networkInfoAdmin": {
          "description": "Admin network addressing information.",
          "type": "string"
        },
        "networkInfoClient": {
          "description": "Client network addressing information.",
          "type": "string"
        },
        "networkInfoGateway": {
          "description": "Gateway network addressing information.",
          "type": "string"
        },
        "networkInfoProvider": {
          "description": "Provider network addressing information.",
          "type": "string"
        },
        "nodeId": {
          "description": "Node ID.",
          "type": "string"
        },
        "regionCode": {
          "description": "Region Code.",
          "type": "string"
        },
        "rootSigningKey": {
          "description": "Retrieval provider Root Signing Public Key.",
          "type": "string"
        },
        "sigingKey": {
          "description": "Used for signing CID Group Offers and Single CID Offers.",
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "ProviderRegister": {
      "description": "Register entry",
      "type": "object",
      "properties": {
        "address": {
          "description": "Filecoin Account to be used with payment channels.",
          "type": "string"
        },
        "networkInfoAdmin": {
          "description": "Admin network addressing information.",
          "type": "string"
        },
        "networkInfoClient": {
          "description": "Client network addressing information.",
          "type": "string"
        },
        "networkInfoGateway": {
          "description": "Gateway network addressing information.",
          "type": "string"
        },
        "nodeId": {
          "description": "Node ID.",
          "type": "string"
        },
        "regionCode": {
          "description": "Region Code.",
          "type": "string"
        },
        "rootSigningKey": {
          "description": "Retrieval provider Root Signing Public Key.",
          "type": "string"
        },
        "sigingKey": {
          "description": "Used for signing CID Group Offers and Single CID Offers.",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Retrieval Providers and Retrieval Gateways register.\n",
    "title": "Filecoin Retrieval Register",
    "version": "0.0.1"
  },
  "basePath": "/",
  "paths": {
    "/": {
      "get": {
        "tags": [
          "Homepage"
        ],
        "summary": "Homepage",
        "operationId": "homepage",
        "responses": {
          "200": {
            "description": "homepage response",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "user validation error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers/gateway": {
      "get": {
        "description": "\u003cb\u003eGet Gateway register list\u003c/b\u003e",
        "tags": [
          "Gateway"
        ],
        "summary": "Get register list",
        "operationId": "getGatewayRegisters",
        "responses": {
          "200": {
            "description": "Gateway register list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GatewayRegister"
              }
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "\u003cb\u003eAdd a Gateway register\u003c/b\u003e",
        "tags": [
          "Gateway"
        ],
        "summary": "Add a Gateway register",
        "operationId": "addGatewayRegister",
        "parameters": [
          {
            "description": "Add a Gateway register",
            "name": "register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/GatewayRegister"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Gateway register added",
            "schema": {
              "$ref": "#/definitions/GatewayRegister"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "\u003cb\u003eDelete Gateway registers\u003c/b\u003e",
        "tags": [
          "Gateway"
        ],
        "summary": "Delete Gateway registers",
        "operationId": "deleteGatewayRegister",
        "responses": {
          "200": {
            "description": "Gateway registers deleted",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers/gateway/{id}": {
      "get": {
        "description": "\u003cb\u003eGet a provider gateway by Id\u003c/b\u003e",
        "tags": [
          "Gateway"
        ],
        "summary": "Get registered Gateway by Id",
        "operationId": "getGatewayRegistersById",
        "parameters": [
          {
            "type": "string",
            "description": "Gateway ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get a registered gateway by Id",
            "schema": {
              "$ref": "#/definitions/GatewayRegister"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers/provider": {
      "get": {
        "description": "\u003cb\u003eGet Provider register list\u003c/b\u003e",
        "tags": [
          "Provider"
        ],
        "summary": "Get Provider register list",
        "operationId": "getProviderRegisters",
        "responses": {
          "200": {
            "description": "Provider register list",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ProviderRegister"
              }
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "post": {
        "description": "\u003cb\u003eAdd a Provider register\u003c/b\u003e",
        "tags": [
          "Provider"
        ],
        "summary": "Add a Provider register",
        "operationId": "addProviderRegister",
        "parameters": [
          {
            "description": "Add a Provider register",
            "name": "register",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProviderRegister"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Provider register added",
            "schema": {
              "$ref": "#/definitions/ProviderRegister"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      },
      "delete": {
        "description": "\u003cb\u003eDelete Provider registers\u003c/b\u003e",
        "tags": [
          "Provider"
        ],
        "summary": "Delete Provider registers",
        "operationId": "deleteProviderRegister",
        "responses": {
          "200": {
            "description": "Provider registers deleted",
            "schema": {
              "$ref": "#/definitions/Ack"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/registers/provider/{id}": {
      "get": {
        "description": "\u003cb\u003eGet a provider register by Id\u003c/b\u003e",
        "tags": [
          "Provider"
        ],
        "summary": "Get registered Provider by Id",
        "operationId": "getProviderRegistersById",
        "parameters": [
          {
            "type": "string",
            "description": "Register ID",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Get a registered provider by Id",
            "schema": {
              "$ref": "#/definitions/ProviderRegister"
            }
          },
          "default": {
            "description": "Internal error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Ack": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "GatewayRegister": {
      "description": "Register entry",
      "type": "object",
      "properties": {
        "address": {
          "description": "Filecoin Account to be used with payment channels.",
          "type": "string"
        },
        "networkInfoAdmin": {
          "description": "Admin network addressing information.",
          "type": "string"
        },
        "networkInfoClient": {
          "description": "Client network addressing information.",
          "type": "string"
        },
        "networkInfoGateway": {
          "description": "Gateway network addressing information.",
          "type": "string"
        },
        "networkInfoProvider": {
          "description": "Provider network addressing information.",
          "type": "string"
        },
        "nodeId": {
          "description": "Node ID.",
          "type": "string"
        },
        "regionCode": {
          "description": "Region Code.",
          "type": "string"
        },
        "rootSigningKey": {
          "description": "Retrieval provider Root Signing Public Key.",
          "type": "string"
        },
        "sigingKey": {
          "description": "Used for signing CID Group Offers and Single CID Offers.",
          "type": "string"
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "ProviderRegister": {
      "description": "Register entry",
      "type": "object",
      "properties": {
        "address": {
          "description": "Filecoin Account to be used with payment channels.",
          "type": "string"
        },
        "networkInfoAdmin": {
          "description": "Admin network addressing information.",
          "type": "string"
        },
        "networkInfoClient": {
          "description": "Client network addressing information.",
          "type": "string"
        },
        "networkInfoGateway": {
          "description": "Gateway network addressing information.",
          "type": "string"
        },
        "nodeId": {
          "description": "Node ID.",
          "type": "string"
        },
        "regionCode": {
          "description": "Region Code.",
          "type": "string"
        },
        "rootSigningKey": {
          "description": "Retrieval provider Root Signing Public Key.",
          "type": "string"
        },
        "sigingKey": {
          "description": "Used for signing CID Group Offers and Single CID Offers.",
          "type": "string"
        }
      }
    }
  }
}`))
}
