// Code generated by go-swagger; DO NOT EDIT.

package registers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ConsenSys/fc-retrieval-register/models"
)

// GetRegistersOKCode is the HTTP code returned for type GetRegistersOK
const GetRegistersOKCode int = 200

/*GetRegistersOK Register list

swagger:response getRegistersOK
*/
type GetRegistersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Register `json:"body,omitempty"`
}

// NewGetRegistersOK creates GetRegistersOK with default headers values
func NewGetRegistersOK() *GetRegistersOK {

	return &GetRegistersOK{}
}

// WithPayload adds the payload to the get registers o k response
func (o *GetRegistersOK) WithPayload(payload []*models.Register) *GetRegistersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get registers o k response
func (o *GetRegistersOK) SetPayload(payload []*models.Register) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegistersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Register, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetRegistersDefault Internal error

swagger:response getRegistersDefault
*/
type GetRegistersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetRegistersDefault creates GetRegistersDefault with default headers values
func NewGetRegistersDefault(code int) *GetRegistersDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRegistersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get registers default response
func (o *GetRegistersDefault) WithStatusCode(code int) *GetRegistersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get registers default response
func (o *GetRegistersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get registers default response
func (o *GetRegistersDefault) WithPayload(payload *models.Error) *GetRegistersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get registers default response
func (o *GetRegistersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegistersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
