# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  utest:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/ConsenSys/fc-retrieval-common/
    steps:
      - checkout
      - run: make utest
  coverage:
    environment:
      CODE_COVERAGE: 80
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/ConsenSys/fc-retrieval-common/
    steps:
      - checkout
      - run:
          name: Check code coverage
          command: |
            make coverage COV=$CODE_COVERAGE

workflows:
  version: 2
  test:
    jobs:
      - utest:
          context:
            - dockerhub-quorumengineering-rw
      - coverage:
          requires:
            - utest
