# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  utest:
    docker:
      - image: circleci/buildpack-deps:stretch
    working_directory: /go/src/github.com/ConsenSys/fc-retrieval-common/
    steps:
      - checkout
      - run: go test ./...

workflows:
  version: 2
  test:
    jobs:
      - utest:
          context:
            - dockerhub-quorumengineering-rw
