# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

jobs:
  utest:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/ConsenSys/fc-retrieval-common/
    steps:
      - checkout
      - run: make utest
  
  coverage:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/ConsenSys/fc-retrieval-common/
    steps:
      - checkout
      - run:
          name: Check code coverage
          command: |
            go test -cover ./...
            echo
            make coverage

workflows:
  version: 2
  test:
    jobs:
      - utest
      - coverage:
          requires:
            - utest
