// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ConsenSys/fc-retrieval-register/models"
)

// DeleteGatewayRegisterOKCode is the HTTP code returned for type DeleteGatewayRegisterOK
const DeleteGatewayRegisterOKCode int = 200

/*DeleteGatewayRegisterOK Gateway registers deleted

swagger:response deleteGatewayRegisterOK
*/
type DeleteGatewayRegisterOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ack `json:"body,omitempty"`
}

// NewDeleteGatewayRegisterOK creates DeleteGatewayRegisterOK with default headers values
func NewDeleteGatewayRegisterOK() *DeleteGatewayRegisterOK {

	return &DeleteGatewayRegisterOK{}
}

// WithPayload adds the payload to the delete gateway register o k response
func (o *DeleteGatewayRegisterOK) WithPayload(payload *models.Ack) *DeleteGatewayRegisterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete gateway register o k response
func (o *DeleteGatewayRegisterOK) SetPayload(payload *models.Ack) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteGatewayRegisterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteGatewayRegisterDefault Internal error

swagger:response deleteGatewayRegisterDefault
*/
type DeleteGatewayRegisterDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteGatewayRegisterDefault creates DeleteGatewayRegisterDefault with default headers values
func NewDeleteGatewayRegisterDefault(code int) *DeleteGatewayRegisterDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteGatewayRegisterDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete gateway register default response
func (o *DeleteGatewayRegisterDefault) WithStatusCode(code int) *DeleteGatewayRegisterDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete gateway register default response
func (o *DeleteGatewayRegisterDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete gateway register default response
func (o *DeleteGatewayRegisterDefault) WithPayload(payload *models.Error) *DeleteGatewayRegisterDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete gateway register default response
func (o *DeleteGatewayRegisterDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteGatewayRegisterDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
