// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ConsenSys/fc-retrieval/register/models"
)

// GetGatewayRegistersOKCode is the HTTP code returned for type GetGatewayRegistersOK
const GetGatewayRegistersOKCode int = 200

/*GetGatewayRegistersOK Gateway register list

swagger:response getGatewayRegistersOK
*/
type GetGatewayRegistersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.GatewayRegister `json:"body,omitempty"`
}

// NewGetGatewayRegistersOK creates GetGatewayRegistersOK with default headers values
func NewGetGatewayRegistersOK() *GetGatewayRegistersOK {

	return &GetGatewayRegistersOK{}
}

// WithPayload adds the payload to the get gateway registers o k response
func (o *GetGatewayRegistersOK) WithPayload(payload []*models.GatewayRegister) *GetGatewayRegistersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get gateway registers o k response
func (o *GetGatewayRegistersOK) SetPayload(payload []*models.GatewayRegister) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGatewayRegistersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.GatewayRegister, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetGatewayRegistersDefault Internal error

swagger:response getGatewayRegistersDefault
*/
type GetGatewayRegistersDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetGatewayRegistersDefault creates GetGatewayRegistersDefault with default headers values
func NewGetGatewayRegistersDefault(code int) *GetGatewayRegistersDefault {
	if code <= 0 {
		code = 500
	}

	return &GetGatewayRegistersDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get gateway registers default response
func (o *GetGatewayRegistersDefault) WithStatusCode(code int) *GetGatewayRegistersDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get gateway registers default response
func (o *GetGatewayRegistersDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get gateway registers default response
func (o *GetGatewayRegistersDefault) WithPayload(payload *models.Error) *GetGatewayRegistersDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get gateway registers default response
func (o *GetGatewayRegistersDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGatewayRegistersDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
