// Code generated by go-swagger; DO NOT EDIT.

package gateway

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGatewayRegistersHandlerFunc turns a function with the right signature into a get gateway registers handler
type GetGatewayRegistersHandlerFunc func(GetGatewayRegistersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGatewayRegistersHandlerFunc) Handle(params GetGatewayRegistersParams) middleware.Responder {
	return fn(params)
}

// GetGatewayRegistersHandler interface for that can handle valid get gateway registers params
type GetGatewayRegistersHandler interface {
	Handle(GetGatewayRegistersParams) middleware.Responder
}

// NewGetGatewayRegisters creates a new http.Handler for the get gateway registers operation
func NewGetGatewayRegisters(ctx *middleware.Context, handler GetGatewayRegistersHandler) *GetGatewayRegisters {
	return &GetGatewayRegisters{Context: ctx, Handler: handler}
}

/* GetGatewayRegisters swagger:route GET /registers/gateway Gateway getGatewayRegisters

Get register list

<b>Get Gateway register list</b>

*/
type GetGatewayRegisters struct {
	Context *middleware.Context
	Handler GetGatewayRegistersHandler
}

func (o *GetGatewayRegisters) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetGatewayRegistersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
