version: "3.8"

services:
  client-js:
    image: ${CLIENT_JS_IMAGE:-consensys/fc-retrieval-client-js:dev}
    container_name: client-js
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    name: shared
    external: true
