# Copyright (C) 2020 ConsenSys Software Inc.
# Docker file used for creating run-time docker image.
# Use a minimalist base image.
FROM scratch

# Put in the settings file needed at runtime.
ADD settings.json /etc/itest/

# Put in trusted anchors / certificates.
#ADD ca-certificates.crt /etc/ssl/certs/

# Add the binary
ADD itest /

# Run the binary when the container starts.
WORKDIR /
CMD ["/itest"]
#EXPOSE 8080 
