version: "3.8"
services:
  itest:
    image: fc-retrieval-itest:v1
    container_name: itest
    ports:
      - "80:80"
      - "443:443"
      - "8090:8090"
      - "8091:8091"
    networks:
      - shared
    depends_on: 
      - gateway
                
  gateway:
    image: fc-retrieval-gateway:v1
    container_name: gateway
    networks:
      - shared

#  dbg:
#   image: busybox
#   #image: radial/busyboxplus:curl
#   container_name: dbg
#   stdin_open: true
#   tty: true
#   networks:
#     - shared
     
networks:
  shared:
