// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ConsenSys/fc-retrieval/register/restapi/operations/gateway"
	"github.com/ConsenSys/fc-retrieval/register/restapi/operations/homepage"
	"github.com/ConsenSys/fc-retrieval/register/restapi/operations/provider"
)

// NewRegisterAPI creates a new Register instance
func NewRegisterAPI(spec *loads.Document) *RegisterAPI {
	return &RegisterAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		GatewayAddGatewayRegisterHandler: gateway.AddGatewayRegisterHandlerFunc(func(params gateway.AddGatewayRegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation gateway.AddGatewayRegister has not yet been implemented")
		}),
		ProviderAddProviderRegisterHandler: provider.AddProviderRegisterHandlerFunc(func(params provider.AddProviderRegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation provider.AddProviderRegister has not yet been implemented")
		}),
		GatewayDeleteGatewayRegisterHandler: gateway.DeleteGatewayRegisterHandlerFunc(func(params gateway.DeleteGatewayRegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation gateway.DeleteGatewayRegister has not yet been implemented")
		}),
		ProviderDeleteProviderRegisterHandler: provider.DeleteProviderRegisterHandlerFunc(func(params provider.DeleteProviderRegisterParams) middleware.Responder {
			return middleware.NotImplemented("operation provider.DeleteProviderRegister has not yet been implemented")
		}),
		GatewayGetGatewayRegistersHandler: gateway.GetGatewayRegistersHandlerFunc(func(params gateway.GetGatewayRegistersParams) middleware.Responder {
			return middleware.NotImplemented("operation gateway.GetGatewayRegisters has not yet been implemented")
		}),
		GatewayGetGatewayRegistersByIDHandler: gateway.GetGatewayRegistersByIDHandlerFunc(func(params gateway.GetGatewayRegistersByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation gateway.GetGatewayRegistersByID has not yet been implemented")
		}),
		ProviderGetProviderRegistersHandler: provider.GetProviderRegistersHandlerFunc(func(params provider.GetProviderRegistersParams) middleware.Responder {
			return middleware.NotImplemented("operation provider.GetProviderRegisters has not yet been implemented")
		}),
		ProviderGetProviderRegistersByIDHandler: provider.GetProviderRegistersByIDHandlerFunc(func(params provider.GetProviderRegistersByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation provider.GetProviderRegistersByID has not yet been implemented")
		}),
		HomepageHomepageHandler: homepage.HomepageHandlerFunc(func(params homepage.HomepageParams) middleware.Responder {
			return middleware.NotImplemented("operation homepage.Homepage has not yet been implemented")
		}),
	}
}

/*RegisterAPI Retrieval Providers and Retrieval Gateways register.
 */
type RegisterAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// GatewayAddGatewayRegisterHandler sets the operation handler for the add gateway register operation
	GatewayAddGatewayRegisterHandler gateway.AddGatewayRegisterHandler
	// ProviderAddProviderRegisterHandler sets the operation handler for the add provider register operation
	ProviderAddProviderRegisterHandler provider.AddProviderRegisterHandler
	// GatewayDeleteGatewayRegisterHandler sets the operation handler for the delete gateway register operation
	GatewayDeleteGatewayRegisterHandler gateway.DeleteGatewayRegisterHandler
	// ProviderDeleteProviderRegisterHandler sets the operation handler for the delete provider register operation
	ProviderDeleteProviderRegisterHandler provider.DeleteProviderRegisterHandler
	// GatewayGetGatewayRegistersHandler sets the operation handler for the get gateway registers operation
	GatewayGetGatewayRegistersHandler gateway.GetGatewayRegistersHandler
	// GatewayGetGatewayRegistersByIDHandler sets the operation handler for the get gateway registers by Id operation
	GatewayGetGatewayRegistersByIDHandler gateway.GetGatewayRegistersByIDHandler
	// ProviderGetProviderRegistersHandler sets the operation handler for the get provider registers operation
	ProviderGetProviderRegistersHandler provider.GetProviderRegistersHandler
	// ProviderGetProviderRegistersByIDHandler sets the operation handler for the get provider registers by Id operation
	ProviderGetProviderRegistersByIDHandler provider.GetProviderRegistersByIDHandler
	// HomepageHomepageHandler sets the operation handler for the homepage operation
	HomepageHomepageHandler homepage.HomepageHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *RegisterAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *RegisterAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *RegisterAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *RegisterAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *RegisterAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *RegisterAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *RegisterAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *RegisterAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *RegisterAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the RegisterAPI
func (o *RegisterAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.GatewayAddGatewayRegisterHandler == nil {
		unregistered = append(unregistered, "gateway.AddGatewayRegisterHandler")
	}
	if o.ProviderAddProviderRegisterHandler == nil {
		unregistered = append(unregistered, "provider.AddProviderRegisterHandler")
	}
	if o.GatewayDeleteGatewayRegisterHandler == nil {
		unregistered = append(unregistered, "gateway.DeleteGatewayRegisterHandler")
	}
	if o.ProviderDeleteProviderRegisterHandler == nil {
		unregistered = append(unregistered, "provider.DeleteProviderRegisterHandler")
	}
	if o.GatewayGetGatewayRegistersHandler == nil {
		unregistered = append(unregistered, "gateway.GetGatewayRegistersHandler")
	}
	if o.GatewayGetGatewayRegistersByIDHandler == nil {
		unregistered = append(unregistered, "gateway.GetGatewayRegistersByIDHandler")
	}
	if o.ProviderGetProviderRegistersHandler == nil {
		unregistered = append(unregistered, "provider.GetProviderRegistersHandler")
	}
	if o.ProviderGetProviderRegistersByIDHandler == nil {
		unregistered = append(unregistered, "provider.GetProviderRegistersByIDHandler")
	}
	if o.HomepageHomepageHandler == nil {
		unregistered = append(unregistered, "homepage.HomepageHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *RegisterAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *RegisterAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *RegisterAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *RegisterAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *RegisterAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *RegisterAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the register API
func (o *RegisterAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *RegisterAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/registers/gateway"] = gateway.NewAddGatewayRegister(o.context, o.GatewayAddGatewayRegisterHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/registers/provider"] = provider.NewAddProviderRegister(o.context, o.ProviderAddProviderRegisterHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/registers/gateway"] = gateway.NewDeleteGatewayRegister(o.context, o.GatewayDeleteGatewayRegisterHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/registers/provider"] = provider.NewDeleteProviderRegister(o.context, o.ProviderDeleteProviderRegisterHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/registers/gateway"] = gateway.NewGetGatewayRegisters(o.context, o.GatewayGetGatewayRegistersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/registers/gateway/{id}"] = gateway.NewGetGatewayRegistersByID(o.context, o.GatewayGetGatewayRegistersByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/registers/provider"] = provider.NewGetProviderRegisters(o.context, o.ProviderGetProviderRegistersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/registers/provider/{id}"] = provider.NewGetProviderRegistersByID(o.context, o.ProviderGetProviderRegistersByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"][""] = homepage.NewHomepage(o.context, o.HomepageHomepageHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *RegisterAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *RegisterAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *RegisterAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *RegisterAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *RegisterAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
