version: "3"
services:
  provider:
    container_name: fc-retrieval-provider
    build:
      dockerfile: provider/Dockerfile
      context: ..
    ports:
      - "${BIND_REST_API}:${BIND_REST_API}"
      - "${BIND_GATEWAY_API}:${BIND_GATEWAY_API}"
      - "${BIND_ADMIN_API}:${BIND_ADMIN_API}"
    volumes:
      - ./logs:${LOG_DIR}
      - ./common:/go/src/github.com/ConsenSys/fc-retrieval/common
      - ./provider:/go/src/github.com/ConsenSys/fc-retrieval/provider
    env_file:
      - .env
    environment:
      - REGISTER_API_URL=http://register:9020
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    name: shared
    external: true
