version: "3.8"

services:
  provider:
    image: consensys/fc-retrieval-provider:dev
    container_name: provider
    networks:
      - shared
    ports:
      - "${BIND_CLIENT_API}:${BIND_CLIENT_API}"
      - "${BIND_PROVIDER_API}:${BIND_PROVIDER_API}"
      - "${BIND_GATEWAY_API}:${BIND_GATEWAY_API}"
      - "${BIND_ADMIN_API}:${BIND_ADMIN_API}"
    env_file:
      - .env
     
networks:
  shared:
    name: shared
    external: true
