version: "3.8"

services:
  provider:
    image: consensys/fc-retrieval-provider:dev
    container_name: provider
    networks:
      - shared
    ports:
      - "${SERVICE_PORT}:80"
    env_file:
      - .env
     
networks:
  shared:
    name: shared
    external: true
