FROM golang:latest

RUN apt-get update && apt-get install make bash

WORKDIR /go/src/app

COPY . .

RUN go mod download -x

COPY --from=itinance/swag /root/swag /usr/local/bin

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -exclude-dir=.git -exclude-dir=docs --build="make build-dev" --command="./main"
