version: "3.8"

services:
  provider:
    image: fc-retrieval-provider:v1
    container_name: provider
    networks:
      - shared
    ports:
      - "${SERVICE_PORT}:80"
    env_file:
      - .env
     
networks:
  shared:
