// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Register Register entry
//
// swagger:model Register
type Register struct {

	// Filecoin Account to be used with payment channels.
	Address string `json:"address,omitempty"`

	// Network addressing information.
	NetworkInfo string `json:"networkInfo,omitempty"`

	// Region Code.
	RegionCode string `json:"regionCode,omitempty"`

	// Retrieval provider Root Signing Public Key.
	RootSigningKey string `json:"rootSigningKey,omitempty"`

	// Used for signing CID Group Offers and Single CID Offers.
	SigingKey string `json:"sigingKey,omitempty"`
}

// Validate validates this register
func (m *Register) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Register) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Register) UnmarshalBinary(b []byte) error {
	var res Register
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
